Added AuthorisationPermissionMismatch to the exclusion criteria on St…
JulianHayward/Azure-MG-Sub-Governance-Reporting pull request #144
Opened 2022-11-01 01:07 UTC by emt2600

Added AuthorisationPermissionMismatch to the exclusion criteria on Storage Account Analysis to prevent failure when a databricks storage account is present

2022-11-01 07:47 UTC, JulianHayward commented on pwsh/dev/functions/processStorageAccountAnalysis.ps1
> +                if ($saProperties -eq 'AuthorizationFailure' -or $saProperties -eq 'AuthorizationPermissionDenied' -or $saProperties -eq 'ResourceUnavailable' or $saProperties -eq 'AuthorizationPermi
-or

2022-11-01 07:47 UTC, JulianHayward requested changes
-or

2022-11-03 00:28 UTC, emt2600 commented on pwsh/dev/functions/processStorageAccountAnalysis.ps1
> +                if ($saProperties -eq 'AuthorizationFailure' -or $saProperties -eq 'AuthorizationPermissionDenied' -or $saProperties -eq 'ResourceUnavailable' or $saProperties -eq 'AuthorizationPermi
updated

2022-11-03 08:09 UTC, MarcelHeek commented
Not sure wheter this is in the same script context, but sometimes I get fatal error on this in the Storage Analysis section with `Unexpected Error`

..........
careblob get restype=service&comp=properties #1 'Unexpected Error' occurred (trying 10 times); sleep 2 seconds
Connection timed out
careblob get restype=service&comp=properties #2 'Unexpected Error' occurred (trying 10 times); sleep 3 seconds
Connection timed out
 careblob get restype=service&comp=properties #3 'Unexpected Error' occurred (trying 10 times); sleep 5 seconds
Connection timed out
  Forced DEBUG: careblob get restype=service&comp=properties -> attempt#4 processing: careblob get restype=service&comp=properties uri: 'https://careblob.blob.core.windows.net/?restype=service&comp=properties'
  Forced DEBUG: careblob get restype=service&comp=properties -> unexpectedError: true
 careblob get restype=service&comp=properties #4 'Unexpected Error' occurred (trying 10 times); sleep 7 seconds
......... 
Connection timed out
  Forced DEBUG: careblob get restype=service&comp=properties -> attempt#11 processing: careblob get restype=service&comp=properties uri: 'https://careblob.blob.core.windows.net/?restype=service&comp=properties'
  Forced DEBUG: careblob get restype=service&comp=properties -> unexpectedError: true
 careblob get restype=service&comp=properties #11 'Unexpected Error' occurred (tried 5 times)/exit
Exception: /home/runner/work/azure-governance-visualizer/azure-governance-visualizer/tools/pwsh/AzGovVizParallel.ps1:11310
 Line |
11310 |          $storageAccounts | ForEach-Object -Parallel ***
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Error - check the last console output for details

2022-11-04 05:48 UTC, merged